### ISSUE TITLE
Babel does not transform object rest spread

### ISSUE THREAD

**Issue by ccschneidr** [aikoven/typescript-immutable-utils#2]
Hi. I really like your approach for TS immutable objects. It straight forward.
Unfortunately the package gives me some headaches regarding Babel. It does not transform the files in the es/ directory but simply puts them into the bundle (with all that const, let, ... etc.). This in turn causes IE11 to choke on the object rest spread (...items), obviously. On the other hand Babel does the transform for other modules and the project source. That's why I suspect an issue with the package.json.
When I remove the line
  "module": "es/index.js",
from package.json everything is fine (because it does not use the es/ files any more but the lib/). But I'm not a webpack expert... maybe this is caused by still using the deprecated Webpack es2015 babel preset? Or can you fix this in the npm?

Best regards,
Christian

**Comment by aikoven** [comment]
Hi Christian,

Thanks for your interest.

It is an issue with `es` build, which should be the same as `commonjs` build except for the module system, i.e. it should still be transpiled down to ES5.

I have fixed it and published a new version. Please try `typescript-immutable-utils@0.1.1`.

**Comment by ccschneidr** [comment]
With the new version it's fine. Thanks for your very fast reaction!
